// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCErHvu5PiG2bmO_glJ0xZc2PachHLJ4zM',
    appId: '1:385000519422:web:2583df2fa1f027f3e957af',
    messagingSenderId: '385000519422',
    projectId: 'my-first-firebase-projec-1a0b1',
    authDomain: 'my-first-firebase-projec-1a0b1.firebaseapp.com',
    storageBucket: 'my-first-firebase-projec-1a0b1.appspot.com',
    measurementId: 'G-HWLRKF1B6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuvRaJrR6TJsZHiyZZtOerlr67MUypN7Y',
    appId: '1:385000519422:android:4e0456902426bca5e957af',
    messagingSenderId: '385000519422',
    projectId: 'my-first-firebase-projec-1a0b1',
    storageBucket: 'my-first-firebase-projec-1a0b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ZCTnX4kD8XFnd9k36qLdyOQ5VokXDb8',
    appId: '1:385000519422:ios:99b5f2a1d66e622ee957af',
    messagingSenderId: '385000519422',
    projectId: 'my-first-firebase-projec-1a0b1',
    storageBucket: 'my-first-firebase-projec-1a0b1.appspot.com',
    iosClientId: '385000519422-3fbg253judb764dc9kk267mr3hg2kd5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirbase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ZCTnX4kD8XFnd9k36qLdyOQ5VokXDb8',
    appId: '1:385000519422:ios:99b5f2a1d66e622ee957af',
    messagingSenderId: '385000519422',
    projectId: 'my-first-firebase-projec-1a0b1',
    storageBucket: 'my-first-firebase-projec-1a0b1.appspot.com',
    iosClientId: '385000519422-3fbg253judb764dc9kk267mr3hg2kd5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirbase1',
  );
}
